language: node_js
sudo: false

node_js:
- '4.0'

git:
    depth: 3

branches:
    only:
        - master
        - stable
    
addons:
    apt:
        sources:
            - naturaldocs
            - ant
            
script:
- ant build-docs
