language: node_js
sudo: required

node_js:
- "0.10"

git:
    depth: 3

branches:
    only:
        - master
        - stable
    
addons:
    apt:
        sources:
            - naturaldocs
            - ant
            
script:
- sudo apt-get install -y naturaldocs
- ant build-docs
